server:
  port: 8080
  
spring:
  datasource:
    # 返回影响的行数，设置时区为【上海】
    url:               jdbc:mysql://47.94.5.149:3306/group_blog?useAffectedRows=true&serverTimezone=Asia/Shanghai
    username:          group_blog
    password:          grouppass
    driver-class-name: com.mysql.cj.jdbc.Driver
    
# mybatis
mybatis:
  #  configuration:
  #    # 开启驼峰命名
  #    map-underscore-to-camel-case: true
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml


  